/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring */

#ifndef _Included_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
#define _Included_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_init
  (JNIEnv *, jclass);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    initStorage
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_initStorage
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    addItem
 * Signature: (JIIII[I[I[Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_addItem
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jintArray, jintArray, jobjectArray, jfloatArray);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    completeLoadData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_completeLoadData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    setSortingIndex
 * Signature: (JLjava/lang/String;[I)J
 */
JNIEXPORT jlong JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_setSortingIndex
  (JNIEnv *, jclass, jlong, jstring, jintArray);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    lookupProducts
 * Signature: (JLjava/lang/String;Z[Ljava/lang/String;[F[FLjava/lang/String;ZII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_lookupProducts
  (JNIEnv *, jclass, jlong, jstring, jboolean, jobjectArray, jfloatArray, jfloatArray, jstring, jboolean, jint, jint);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    getSimilarProducts
 * Signature: (JII[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_getSimilarProducts
  (JNIEnv *, jclass, jlong, jint, jint, jintArray);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    countProducts
 * Signature: (JLjava/lang/String;[IIZ[Ljava/lang/String;[F[F)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_countProducts
  (JNIEnv *, jclass, jlong, jstring, jintArray, jint, jboolean, jobjectArray, jfloatArray, jfloatArray);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    countAllProducts
 * Signature: (JZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_countAllProducts
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ua_com_ubuntuzone_features_ProductFeaturesNativeRoaring_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
